# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/boki/downl/.prog/clion/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/boki/downl/.prog/clion/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/boki/proj/HackTUES-6

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/boki/proj/HackTUES-6/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/boki/downl/.prog/clion/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/boki/downl/.prog/clion/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/boki/proj/HackTUES-6/cmake-build-debug/CMakeFiles /home/boki/proj/HackTUES-6/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/boki/proj/HackTUES-6/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HackTUES_6

# Build rule for target.
HackTUES_6: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HackTUES_6
.PHONY : HackTUES_6

# fast build rule for target.
HackTUES_6/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/build
.PHONY : HackTUES_6/fast

src/block.o: src/block.cpp.o

.PHONY : src/block.o

# target to build an object file
src/block.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/block.cpp.o
.PHONY : src/block.cpp.o

src/block.i: src/block.cpp.i

.PHONY : src/block.i

# target to preprocess a source file
src/block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/block.cpp.i
.PHONY : src/block.cpp.i

src/block.s: src/block.cpp.s

.PHONY : src/block.s

# target to generate assembly for a file
src/block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/block.cpp.s
.PHONY : src/block.cpp.s

src/dev.o: src/dev.cpp.o

.PHONY : src/dev.o

# target to build an object file
src/dev.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/dev.cpp.o
.PHONY : src/dev.cpp.o

src/dev.i: src/dev.cpp.i

.PHONY : src/dev.i

# target to preprocess a source file
src/dev.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/dev.cpp.i
.PHONY : src/dev.cpp.i

src/dev.s: src/dev.cpp.s

.PHONY : src/dev.s

# target to generate assembly for a file
src/dev.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/dev.cpp.s
.PHONY : src/dev.cpp.s

src/dsign.o: src/dsign.cpp.o

.PHONY : src/dsign.o

# target to build an object file
src/dsign.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/dsign.cpp.o
.PHONY : src/dsign.cpp.o

src/dsign.i: src/dsign.cpp.i

.PHONY : src/dsign.i

# target to preprocess a source file
src/dsign.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/dsign.cpp.i
.PHONY : src/dsign.cpp.i

src/dsign.s: src/dsign.cpp.s

.PHONY : src/dsign.s

# target to generate assembly for a file
src/dsign.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/dsign.cpp.s
.PHONY : src/dsign.cpp.s

src/entry.o: src/entry.cpp.o

.PHONY : src/entry.o

# target to build an object file
src/entry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/entry.cpp.o
.PHONY : src/entry.cpp.o

src/entry.i: src/entry.cpp.i

.PHONY : src/entry.i

# target to preprocess a source file
src/entry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/entry.cpp.i
.PHONY : src/entry.cpp.i

src/entry.s: src/entry.cpp.s

.PHONY : src/entry.s

# target to generate assembly for a file
src/entry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/entry.cpp.s
.PHONY : src/entry.cpp.s

src/hash.o: src/hash.cpp.o

.PHONY : src/hash.o

# target to build an object file
src/hash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/hash.cpp.o
.PHONY : src/hash.cpp.o

src/hash.i: src/hash.cpp.i

.PHONY : src/hash.i

# target to preprocess a source file
src/hash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/hash.cpp.i
.PHONY : src/hash.cpp.i

src/hash.s: src/hash.cpp.s

.PHONY : src/hash.s

# target to generate assembly for a file
src/hash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/hash.cpp.s
.PHONY : src/hash.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HackTUES_6.dir/build.make CMakeFiles/HackTUES_6.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... HackTUES_6"
	@echo "... src/block.o"
	@echo "... src/block.i"
	@echo "... src/block.s"
	@echo "... src/dev.o"
	@echo "... src/dev.i"
	@echo "... src/dev.s"
	@echo "... src/dsign.o"
	@echo "... src/dsign.i"
	@echo "... src/dsign.s"
	@echo "... src/entry.o"
	@echo "... src/entry.i"
	@echo "... src/entry.s"
	@echo "... src/hash.o"
	@echo "... src/hash.i"
	@echo "... src/hash.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

